/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/echarts/src/BarEchart.vue')['default']
    BaseEchart: typeof import('./src/components/echarts/src/BaseEchart.vue')['default']
    DynamicForm: typeof import('./src/components/form/DynamicForm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    LineEchart: typeof import('./src/components/echarts/src/LineEchart.vue')['default']
    MapEchart: typeof import('./src/components/echarts/src/MapEchart.vue')['default']
    PageContent: typeof import('./src/components/page/PageContent.vue')['default']
    PageDialog: typeof import('./src/components/page/PageDialog.vue')['default']
    PageSearch: typeof import('./src/components/page/PageSearch.vue')['default']
    PieEchart: typeof import('./src/components/echarts/src/PieEchart.vue')['default']
    RoseEchart: typeof import('./src/components/echarts/src/RoseEchart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
