/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/echarts/src/BarEchart.vue')['default']
    BaseEchart: typeof import('./src/components/echarts/src/BaseEchart.vue')['default']
    DynamicForm: typeof import('./src/components/form/DynamicForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    LineEchart: typeof import('./src/components/echarts/src/LineEchart.vue')['default']
    MapEchart: typeof import('./src/components/echarts/src/MapEchart.vue')['default']
    PageContent: typeof import('./src/components/page/PageContent.vue')['default']
    PageDialog: typeof import('./src/components/page/PageDialog.vue')['default']
    PageSearch: typeof import('./src/components/page/PageSearch.vue')['default']
    PieEchart: typeof import('./src/components/echarts/src/PieEchart.vue')['default']
    RoseEchart: typeof import('./src/components/echarts/src/RoseEchart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
